// 사이트의 모든 내용(글·이미지·링크)은 이 파일에서 고치면 됩니다.

// 이미지는 images 폴더에 있어요. img('a7652d_xxx~mv2.png') → images/a7652d_xxx.webp
// (예전 윅스 이름을 그대로 쓰고, 확장자만 .webp로 바뀝니다)
function img(id) {
  return `images/${id.replace(/~mv2/, '').replace(/\.(png|jpe?g)$/i, '')}.webp`;
}

const SITE = {
  name: 'LEE JIHYUN',
  instagram: 'https://www.instagram.com/hi_ixoxi?igsh=cnFoeXE1NWxweGdp',
  avatar: 'a3c153_b79a53f203ca4892958a2fe6e0c9a822~mv2.png',
  avatarHover: 'a3c153_e1410a1d129d42b6b093bf4c361c88ed~mv2.png',
  phone: '010-3351-9976',
  email: 'ixoxi.artison@gmail.com',
  // Contact 폼 → Web3Forms가 위 이메일로 바로 보내 줌 (공개용 키라 사이트에 넣어도 됨)
  formKey: 'fb6821e1-c405-4298-aa91-2c71bea36137',
  year: 2026,
};

// 첫 화면 포스터 슬라이드
const INTRO_SLIDES = [
  'a7652d_cd2a31e8feea43e88e23fd45833e7e1d~mv2.png',
  'a7652d_fb090fa4dba240098bb2eeff75a78277~mv2.png',
  'a7652d_2c850212cb134300b8f3803495a0685e~mv2.png',
  'a7652d_2ecf6b30d9d545cd9711dd01c5294ecb~mv2.png',
  'a7652d_bd46db4ebfcb4ac3804f3f15b962242c~mv2.png',
  'a7652d_a39a54df5d8d497298c1c31d21b3312a~mv2.png',
  'a7652d_09b49ab95d6e489fad228f41809cad1b~mv2.png',
  'a7652d_746eec0279f743ffbf679f8fff9959a6~mv2.png',
  'a7652d_be30121efa06445391aa782cd9554cdb~mv2.png',
  'a7652d_954949d06c1447cf9bda031e806c7ac1~mv2.jpg',
];

// BIO 페이지
const BIO = {
  poster: 'a7652d_5fd921a7f63d425abcee22f4d27bf1e8~mv2.png',
  awards: [
    { title: '디지털인문예술 전시회 포스터 공모전', prize: '최우수상', place: '춘천, 한림대학교', year: '2025', link: 'dah' },
    { title: '일송기념도서관 장서표 디자인 공모전', prize: '최우수상', place: '춘천, 한림대학교', year: '2024', link: 'geumsaek' },
    { title: '2026 디지털인문예술전공 신규 캐릭터 공모전', prize: '우수상', place: '춘천, 한림대학교', year: '2026', link: 'dfoo' },
    { title: '제 18회 디지털인문예술전공 프로젝트 전시회', prize: '우수상', place: '춘천, 한림대학교', year: '2026', link: 'psyche' },
    { title: '제 15회 디지털인문예술 기말프로젝트 전시회', prize: '우수상', place: '춘천, 한림대학교', year: '2024', link: 'i-like' },
    { title: '제 15회 디지털인문예술 기말프로젝트 전시회', prize: '우수상', place: '춘천, 한림대학교', year: '2024', link: 'tagger' },
    { title: '제 13회 디지털인문예술 기말프로젝트 전시회', prize: '장려상', place: '춘천, 한림대학교', year: '2023', link: 'olympos' },
  ],
  exhibitions: [
    { title: '제 13회 디지털인문예술 기말프로젝트 전시회', place: '일송기념도서관 4층 C.SQUARE, 춘천', date: '2023. 11. 28. ~ 11. 30.' },
    { title: '제 14회 디지털인문예술 기말프로젝트 전시회', place: '일송기념도서관 4층 C.SQUARE, 춘천', date: '2024. 06. 03. ~ 06. 05.' },
    { title: '제 15회 디지털인문예술 기말프로젝트 전시회', place: '한림대학교 Campus Life Center 1,2층, 춘천', date: '2024. 12. 03. ~ 12. 06.' },
    { title: '제 16회 디지털인문예술 기말프로젝트 전시회', place: '한림대학교 Campus Life Center 1,2층, 춘천', date: '2025. 06. 03. ~ 06. 05.' },
    { title: '제 18회 디지털인문예술전공 프로젝트 전시회', place: '한림대학교 Campus Life Center 1층, 춘천', date: '2026. 06. 02. ~ 06. 04.' },
  ],
  experience: [
    { title: '한림대학교 박물관 서포터즈 6기', date: '2024. 09. 06. ~ 12. 11.', link: 'supporters' },
    { title: '한림대학교 박물관 보조연구원', date: '2025. 03. 17. ~ 07. 15.', link: 'researcher' },
  ],
  certifications: ['컴퓨터그래픽스운용기능사', 'Microsoft Word Expert', 'Microsoft PowerPoint'],
};

// 포트폴리오 카테고리. items의 id가 PROJECTS의 키. id가 null이면 상세 페이지 없음.
const CATEGORIES = {
  awards: {
    label: 'AWARDS', back: 'Awards', layout: 'grid',
    tile: 'a7652d_9d03a298537c48e29c0b5c3962a4f69a~mv2.jpg',
    items: [
      { id: 'dah', title: '흐르는 경계, DAH', thumb: 'a7652d_5fd921a7f63d425abcee22f4d27bf1e8~mv2.png' },
      { id: 'geumsaek', title: '금색 서정(抒情)', thumb: 'a7652d_fb090fa4dba240098bb2eeff75a78277~mv2.png' },
      { id: 'i-like', title: 'I LIKE', thumb: 'a7652d_2c850212cb134300b8f3803495a0685e~mv2.png' },
      { id: 'tagger', title: 'You are a tagger', thumb: 'a7652d_96594505be83425e8bf6c55893cf906b~mv2.png' },
      { id: 'seocheon', title: '서천일화(花)', thumb: 'a7652d_914b8a19beed4959805b65121ae27b7a~mv2.png' },
      { id: 'olympos', title: '올림포스의 눈과 동심의 여신', thumb: 'a7652d_6c2150db0fdc4dbf83e6f760eaba681a~mv2.png' },
      { id: 'dfoo', title: '디푸(D-Foo)', thumb: 'a7652d_ba711fe6ca634a598d28b551186a987c~mv2.png' },
      { id: 'psyche', title: 'PROJECT: PSYCHE-TYPE', thumb: 'a7652d_3d9ca7e1a44e42588a160d07e70f0c29~mv2.png' },
    ],
  },
  design: {
    label: 'DESIGN', back: 'Design', layout: 'grid',
    tile: 'a7652d_746eec0279f743ffbf679f8fff9959a6~mv2.png',
    items: [
      { id: 'chok', title: '촉 (觸)', thumb: 'chok-poster.png' },
      { id: 'gongmyeong', title: '공명(共鳴): 디지털의 파동', thumb: 'a7652d_746eec0279f743ffbf679f8fff9959a6~mv2.png' },
      { id: 'sinho', title: '신호(信號): 연결의 언어', thumb: 'a7652d_be30121efa06445391aa782cd9554cdb~mv2.png' },
      { id: 'x-gon', title: "X Gon' Give It To Ya", thumb: 'a7652d_09b49ab95d6e489fad228f41809cad1b~mv2.png' },
      { id: 'leon-pro', title: 'LÉON: The Professional', thumb: 'a7652d_954949d06c1447cf9bda031e806c7ac1~mv2.jpg' },
      { id: 'silhouette', title: '지성의 실루엣', thumb: 'a7652d_e23a4a9d4afd42e28151fba5d0f0e4e8~mv2.png' },
      { id: 'leon', title: 'LÉON', thumb: 'a7652d_7dbce06004cb466e80d2f6036ac3521b~mv2.png' },
    ],
  },
  // 게임·웹처럼 직접 만들어서 움직이는 작업 (대표 이미지가 생기면 tile에 넣기)
  interactive: {
    label: 'INTERACTIVE', back: 'Interactive', layout: 'wide',
    tile: 'game-stage3.png',
    items: [
      { id: 'pnr', title: 'POINT OF NO RETURN', date: '2025-2 · 3D게임디자인 기말 프로젝트', thumb: 'game-title.png' },
      { id: 'webbook', title: '작은 동화책 — 연우의 대모험', date: '2023-2 · 창의코딩 기말 프로젝트', thumb: 'webbook-home.png' },
    ],
  },
  experience: {
    label: 'EXPERIENCE', back: 'Experience', layout: 'cards',
    tile: 'a7652d_78c7adbf989c4bceb0380b22ef23122d~mv2.jpg',
    items: [
      { id: 'supporters', title: '한림대학교 박물관 서포터즈 6기', date: '2024. 09. 06. ~ 12. 11.', thumb: 'a7652d_bf216efc99db4651ad091fcaccdc26b5~mv2.png' },
      { id: 'researcher', title: '한림대학교 박물관 보조연구원', date: '2025. 03. 17. ~ 07. 15.', thumb: 'a7652d_dc34229b0a0645c2a60f331daf1f5882~mv2.jpg' },
    ],
  },
  // 작은 작업 모음: 상세 페이지 없이 카드 + 한 줄 설명, 누르면 이미지를 크게 넘겨 봄
  archive: {
    label: 'ARCHIVE', back: 'Archive', layout: 'archive',
    tile: 'archive-shepherd-cover.png',
    items: [
      {
        title: '양치기 소년 — AI 동화책',
        meta: '2026-1 · AI디지털그래픽 기말 과제',
        note: "고전 우화 '양치기 소년'을 어른들을 위한 인생 우화로 재해석한 동화책 디자인. 가상의 출판사 '마녀책방(MANYEO BOOKSHOP)'의 로고·삽화·목업 배경을 Gemini로 만들고, Photoshop으로 표지·내지·목업을 편집했다.",
        images: ['archive-shepherd-cover.png', 'archive-shepherd-page1.png', 'archive-shepherd-page2.png', 'archive-shepherd-logo.png'],
      },
    ],
  },
};
const CATEGORY_ORDER = ['awards', 'design', 'interactive', 'experience', 'archive'];

/*
  작품 상세 페이지.
  body 블록 종류:
    ['h', '제목']          가운데 정렬 소제목
    ['sub', '[ Role ]']     본문 속 굵은 소제목
    ['p', '문단']           본문 (줄바꿈 \n 그대로 표시)
    ['img', id]             큰 이미지
    ['imgs', [id, ...]]     작은 이미지 여러 장 한 줄로
    ['cap', '설명']         이미지 아래 작은 설명
*/
const PROJECTS = {
  dah: {
    cat: 'awards', title: '흐르는 경계, DAH',
    hero: 'a7652d_cd2a31e8feea43e88e23fd45833e7e1d~mv2.png',
    headline: "2025-2 디지털인문예술 전시회 포스터 공모전 '최우수상'",
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 흐르는 경계, DAH >'],
      ['p', '“디지털과 인문의 교차점, 그 유동적인 사유” 디자인, 인문학, 예술의 경계를 허물고 융합하는 DAH(Digital Arts & Humanities) 전공의 정체성을 시각화한 작품이다. 유동적인 금속 재질의 인물을 통해 영역을 넘나드는 창의적 역동성을 표현했다.'],
      ['sub', '[ Meaning ] : 흐르는 경계 (Fluid Boundaries)'],
      ['p', '작품 제목은 고정된 틀에 갇히지 않고 끊임없이 변화하는 지식의 형태를 탐구한다는 의미를 가진다.'],
      ['p', '• [ 유동(流動) ] : 정체되지 않고 흘러내리는 금속 질감을 통해, 기존 학문의 경계를 벗어나 새로운 가치를 모색하는 유연한 사고를 상징.'],
      ['p', "• [ 응시(凝視) ] : 디지털 시대 속에서도 놓치지 않아야 할 '인간성'에 대한 깊은 질문과 성찰을 정면의 시선에 담아내며 '미래 기술과 인간 가치의 융합'이라는 의미가 내포되어있다.\n차가운 디지털 환경 안에서 뜨겁게 요동치는 인간 중심적 미학을 정의했다."],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Fluid Metallic Texture ] | 빛을 반사하는 유동적인 금속 재질을 활용하여 다학제적 융합이 지닌 역동적인 에너지와 미래 지향적 무드를 완성했다.'],
      ['p', '• [ Human-Centric Symbolism ] | 애절한 포즈와 정면의 응시를 통해 기술적 진보 속에서도 변하지 않는 인간의 감정과 사유의 중요성을 상징적으로 배치했다.'],
      ['p', '• [ Contrast of Light & Darkness ] | 암흑 속에서 붉고 푸르게 타오르는 금속의 대비를 통해, 미지의 영역(디지털)을 개척해 나가는 예술적 통찰력을 강조했다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Gemini (Character Concept Generation)\n• Adobe Photoshop (Character Image Editing & Filtering)\n• Adobe Illustrator (Typography, Layout & Vector Graphics)'],
    ],
    links: [['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah-2025-2/about?authuser=1']],
  },

  geumsaek: {
    cat: 'awards', title: '금색 서정(抒情)',
    hero: 'a7652d_fb090fa4dba240098bb2eeff75a78277~mv2.png',
    headline: "2024-2 일송기념도서관 장서표 디자인 공모전 '최우수상'",
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 금색 서정(抒情) >'],
      ['p', '“지혜의 밤을 밝히는 황금빛 기록” 한림대학교 일송기념도서관의 정체성을 현대적인 그래픽 언어로 재해석한 장서표 디자인이다. 고전적 조형미와 도서관의 상징적 요소를 결합해 지식의 영속성을 담아냈다.'],
      ['sub', '[ Meaning ] : 금색 서정(金色 抒情)'],
      ['p', "본 작품의 제목인 '금색 서정'은 시각적인 화려함 속에 담긴 깊은 내면의 울림을 의미한다."],
      ['p', '• [ 금색(金色) ] : 도서관이 지닌 변치 않는 가치와 빛나는 지성을 상징한다.'],
      ['p', "• [ 서정(抒情) ] : 딱딱한 지식의 나열을 넘어, 책과 공간이 주는 정서적 감동과 사색의 시간을 뜻한다. 즉, '황금빛으로 물든 사색의 순간'이라는 의미로, 도서관이라는 지적인 공간에서 마주하는 고요하고도 벅찬 예술적 경험을 정의했다."],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Classic & Modern ] | 아그리파와 이오니아 기둥을 섬세한 라인 아트로 표현하여 시대를 초월한 고전미를 완성했다.'],
      ['p', '• [ Symbolism ] | 도서관의 상징인 ‘일송(一松)’은 학문의 굳건한 의지를, 밤하늘의 달과 별은 진리를 찾는 길잡이를 의미한다.'],
      ['p', '• [ Color Strategy ] | 깊이 있는 딥 네이비와 찬란한 골드의 대비를 통해 소장 가치가 느껴지는 예술적 품격을 강조했다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Typography, Layout, Vector Graphics & Character Artwork)'],
    ],
    links: [['Visit Contest', 'https://sites.google.com/glab.hallym.ac.kr/dah2024-2/공모전']],
  },

  'i-like': {
    cat: 'awards', title: 'I LIKE',
    hero: 'a7652d_2c850212cb134300b8f3803495a0685e~mv2.png',
    headline: "2024-2 제 15회 디지털인문예술 기말프로젝트 전시회 '우수상'",
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < I LIKE >'],
      ['p', '“차가운 메탈릭 속에 숨겨진 뜨거운 예술적 영혼” 대중문화의 상징적 캐릭터인 징징이(Squidward)를 통해 현대인이 지닌 외강내유의 면모를 재해석한 아트워크다. 예민하고 까칠한 겉모습 뒤에 감춰진 다정함과 꿈을 향한 열망을 시각적 대비를 통해 담아냈다.'],
      ['sub', '[ Meaning ] : I LIKE'],
      ['p', "본 작품의 제목인 'I LIKE'는 타인의 시선과 상관없이 자신이 사랑하는 것(예술, 클라리넷, 고독)에 몰두하는 주관적인 만족감을 의미한다."],
      ['p', '• [ I ] : 집단 속에서 소외감을 느끼면서도 독보적인 자아를 유지하려는 개인의 정체성을 상징한다.'],
      ['p', "• [ LIKE ] : 무심한 표정 뒤에 감춰진 미학적 취향과, 일상의 권태를 예술로 승화시키려는 의지를 뜻한다. 즉, '나만의 세계를 향한 무심한 애정'이라는 의미로 해석했다."],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Cold Outside, Warm Inside ] | 징징이의 예민하고 까칠한 성격을 차가운 메탈릭 질감으로 시각화했다. 그러나 이는 단순한 차가움이 아닌, 내면의 꿈을 보호하기 위한 방어기제이자 그가 동경하는 세련된 예술적 감각을 상징한다.'],
      ['p', '• [ Artistic Refinement ] | 예술을 사랑하는 캐릭터의 페르소나에 맞춰, 깔끔하게 정돈된 레이아웃과 빛을 반사하는 반짝이는 타이포그래피를 배치하여 그의 높은 심미안과 정갈한 내면을 표현했다.'],
      ['p', '• [ Metallic & Surreal ] | Cinema 4D를 활용해 비현실적인 크롬 질감을 구현함으로써, 일상적인 캐릭터를 하나의 고결한 예술적 오브제로 격상시켰다.'],
      ['p', '• [ Compositional Contrast ] | 중앙의 정적인 메인 캐릭터와 우측의 동적인 잔상 효과를 대비시켜, 반복되는 현실 속에서도 끊임없이 꿈틀대는 그의 예술적 자아를 형상화했다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Cinema 4D (3D Modeling, Texturing & Rotation Motion)\n• Adobe Illustrator (Typography, Layout & Vector Graphics)\n• Adobe Premiere Pro (Final Video Rendering & Export)'],
    ],
    links: [['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah2024-2/project/디지털디자인2']],
  },

  tagger: {
    cat: 'awards', title: 'You are a tagger',
    hero: 'a7652d_96594505be83425e8bf6c55893cf906b~mv2.png',
    headline: "2024-2 제 15회 디지털인문예술 기말프로젝트 전시회 '우수상'",
    body: [
      ['sub', '[ Team Project ]'],
      ['p', 'Project : < PEEK-A-BOO : You are a tagger >\nTeam : 피자스쿨 (PIZZA SCHOOL)'],
      ['p', "“잔혹한 동화, 오싹한 영혼 술래잡기” 레드벨벳의 '피카부(Peek-A-Boo)' 뮤직비디오 세계관을 OSMU(One Source Multi-Use) 관점에서 재해석한 추리 보드게임 프로젝트이다. 저택이라는 폐쇄된 공간 속에서 벌어지는 미스터리한 사건을 감각적인 그래픽과 긴장감 넘치는 스토리텔링으로 구현했다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Visual Designer (Card Assets & UI) 본 프로젝트에서 게임의 시각적 몰입감을 결정짓는 카드 시스템의 전반적인 디자인을 전담했다.'],
      ['p', '• [ Card Design ] : 캐릭터 카드 및 아이템 카드 5종의 비주얼 컨셉 기획 및 제작'],
      ['p', '• [ Typography ] : 프로젝트의 미스터리한 분위기를 극대화하는 타이포그래피 설계 및 배치'],
      ['h', '[ Card Deck Design ]'],
      ['img', 'a7652d_e177e3d76ace4976a0700395c0eb5792~mv2.png'],
      ['img', 'a7652d_42a6fb08106e4e908ea2d071d54df062~mv2.png'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Visual Identity ] : 전체적으로 어둡고 거친 질감(Grunge Texture)의 블랙 배경에 화려한 문양의 프레임을 대조시켜, 고전적이면서도 기괴한 저택의 분위기를 일관되게 유지했다.'],
      ['p', '• [ Asset Design ] : 도끼(Axe), 검정 젤리(Black Jelly) 등 게임의 핵심 오브젝트를 반짝이는 입체감으로 표현하여 다크한 배경 속에서도 사용자의 시선이 집중되도록 설계했다.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Gothic Grunge Style ] | 세월의 흔적이 느껴지는 거친 텍스처와 화려한 바로크풍 프레임을 결합하여 보드게임 특유의 고전적인 고급스러움과 공포감을 동시에 연출했다.'],
      ['p', '• [ Symbolic Object ] | 게임 내 단서가 되는 아이템들은 강렬한 하이라이트 효과를 주어 가독성을 높였으며, 각 카드의 상징성을 직관적으로 전달했다.'],
      ['sub', '[ Storytelling ]'],
      ['p', '보름달이 뜨던 밤, 저택에서 사라진 배달부. 소녀들 중 누가 유령이고 누가 범인인지 모르는 채 단서를 찾아 어두운 복도를 거닐어야 한다. 과연 진실을 마주할 진짜는 누구인가?'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Typography, Vector Graphics & Shining Decorative Elements)\n• Adobe Photoshop (Card Layout Design, Frame Compositing & Visual Effects)'],
    ],
    links: [
      ['View Game Guide', 'https://qr.me-qr.com/mobile/pdf/883b1356-6ec4-4169-adbf-922d85adbfff'],
      ['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah2024-2/project/대중서사양식의-이해/피카부peek-a-boo-you-are-a-tagger'],
    ],
  },

  seocheon: {
    cat: 'awards', title: '서천일화(花)',
    hero: 'a7652d_914b8a19beed4959805b65121ae27b7a~mv2.png',
    headline: "2025-1 제 16회 디지털인문예술 기말프로젝트 전시회 '우수상'",
    body: [
      ['sub', '[ Team Project ]'],
      ['p', 'Project : 서천일화(花)\nTeam : 언더월드 (UNDER WORLD)'],
      ['p', '“이승도 저승도 아닌 생명의 공간, 서천꽃밭의 진실을 파헤치다.” 한국 신화인 <명진국생불왕본풀이>와 <이공본풀이>를 현대적으로 재해석한 2D 로프 플랫폼 어드벤처 게임이다. 사라진 주인공과 꽃밭 속에 감춰진 비극적 서사를 미스터리한 분위기와 독창적인 내러티브로 풀어냈다.'],
      ['sub', '[ Role ]'],
      ['p', 'Lead Brand & Identity Designer (Logo, Typography & Identity Applications) 본 프로젝트의 핵심 비주얼 아이덴티티인 공식 로고와 타이포그래피 시스템 구축을 전담하였으며, 브랜드 확장성 제안을 위한 목업 작업을 수행하였습니다.'],
      ['p', "• [ Logo Design ] : 게임의 핵심 오브젝트인 '꽃'을 활용한 심볼릭 로고 기획 및 제작"],
      ['p', '• [ Visual Branding ] : 한국적 미장센과 판타지 요소를 결합한 메인 타이틀 타이포그래피 설계'],
      ['p', '• [ Mock-up Application ] : 오프라인 매체(단행본)의 비주얼 구현.'],
      ['h', '[ Graphic Design ]'],
      ['img', 'a7652d_9430dbc254204d90a2b1134870096aa2~mv2.png'],
      ['img', 'a7652d_525c0cc281e34965915d46153a0046e5~mv2.png'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Symbol System ] : 게임 내 주요 소재인 은방울꽃, 아마릴리스 등을 기하학적이고 현대적인 심볼로 추상화하여, 게임의 인벤토리 UI 및 굿즈 등에 범용적으로 사용 가능한 로고 시스템을 구축했다.'],
      ['p', "• [ Identity Integration ] : 심볼의 곡선 요소와 타이틀 서체의 날카로운 획을 통일감 있게 설계하여, 서천꽃밭이라는 공간이 가진 '생명력'과 '비극적 서사'라는 이중적 메시지를 시각적으로 통합했다."],
      ['p', '• [ Visual Extension ] : 로고와 타이포그래피가 실제 단행본 및 아트북에 적용되었을 때의 입체감과 질감을 목업 작업을 통해 시각화하여, 프로젝트의 브랜드 가치와 확장 가능성을 증명했다.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Modern Orientalism ] | 서예의 역동적인 필법(Stroke)을 현대적인 벡터 그래픽으로 재해석하여, 고전적인 우아함과 세련된 판타지 무드를 동시에 구현했다.'],
      ['p', "• [ Organic Typography ] | '화(花)'라는 주제에 맞춰 글자의 자음과 모음 끝부분을 식물의 줄기와 잎사귀 형태로 유기적으로 연결, 타이틀 자체를 하나의 예술적인 오브젝트로 디자인했다."],
      ['sub', '[ Storytelling ]'],
      ['p', '서천꽃밭의 다음 꽃감관 후보로 발탁된 주인공. 하지만 어느 날 갑자기 사라진 주인공과 불타버린 꽃밭. 저승도 이승도 아닌 곳에서 당신은 흩어진 꽃잎 뒤에 숨겨진 잔혹하고도 아름다운 진실을 마주하게 된다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Main Logo & Typography Design, Vector Graphics)\n• Adobe Photoshop (Mock-up Digital Imaging)'],
    ],
    links: [
      ['Visit Game Site', 'https://underworld004.creatorlink.net/'],
      ['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah-2025-1/project/한국문화와-콘텐츠개발/서천일화花'],
    ],
  },

  olympos: {
    cat: 'awards', title: '올림포스의 눈과 동심의 여신',
    hero: 'a7652d_6c2150db0fdc4dbf83e6f760eaba681a~mv2.png',
    headline: "2023-2 제 13회 디지털인문예술 기말프로젝트 전시회 '장려상'",
    body: [
      ['sub', '[ Team Project ]'],
      ['p', 'Project : 올림포스의 눈과 동심의 여신\nTeam : 노보(NOVO)'],
      ['p', '“새하얀 겨울, 아이들의 웃음소리를 사랑하는 여신.” 그리스 신화적 모티프와 창작 설정을 결합하여 탄생시킨 여신 ‘프뤽사’의 비주얼 스토리텔링 프로젝트이다. 순수함과 차가운 겨울의 이미지를 대조적인 컬러와 섬세한 소품 설정을 통해 입체적으로 구현했다.'],
      ['sub', '[ Role ]'],
      ['p', 'Lead Character Artist & Asset Designer 본 프로젝트의 메인 캐릭터 ‘프뤽사’의 비주얼 컨셉 기획과 캐릭터 드로잉, 그리고 세계관을 구성하는 주요 오브젝트 일러스트를 전담했다.'],
      ['p', '• [ Character Design ] : 백발과 적안, 서리 낀 로브 등 캐릭터의 외형적 특징과 고유한 비주얼 정체성 설계.'],
      ['p', '• [ Character Illustration ] : 캐릭터의 성격과 분위기를 극대화한 메인 전신 일러스트 제작.'],
      ['p', '• [ Object Illustration ] : {얼린 낙상홍 열매}, {눈토끼}, {낙상홍 브로치} 등 세계관의 디테일을 완성하는 핵심 오브젝트 드로잉.'],
      ['h', '[ Character Design & 2D Illustrator ]'],
      ['img', 'a7652d_dc4504ffe1574174897ac6df33cd01f1~mv2.png'],
      ['img', 'a7652d_fcbc999aaf414fcdaf9aa5ce8c484ca2~mv2.png'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Visual Identity Construction ] : ‘동심’과 ‘겨울’이라는 키워드를 시각화하기 위해 푸른색과 붉은색의 대비를 활용하여 독보적인 캐릭터 이미지를 구축했다.'],
      ['p', '• [ Detail-Oriented Assets ] : 캐릭터의 서사를 뒷받침하는 소품들을 정교한 일러스트로 구현하여, 세계관의 몰입도를 높이고 캐릭터의 완성도를 보완했다.'],
      ['p', '• [ Concept Alignment ] : 기획 의도에 맞는 캐릭터의 표정과 동세, 아이템 배치를 통해 프로젝트의 시각적 메세지를 일관되게 전달했다.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Frosty & Pure Aesthetic ] | 눈처럼 새하얀 피부와 비단실 같은 머리카락 표현을 통해 신비롭고 순수한 여신의 이미지를 정의했다.'],
      ['p', '• [ Symbolic Palette ] | 캐릭터의 눈동자와 낙상홍 열매에 강렬한 레드 포인트를 주어 시선을 집중시키고, 차가운 톤의 의상과 대조시켜 캐릭터의 상징성을 강조했다.'],
      ['sub', '[ Storytelling ]'],
      ['p', '겨울이 되면 지상으로 내려와 하얀 눈을 내리는 어린 소녀 모습의 여신, 프뤽사. 아이들의 맑은 웃음을 사랑하는 그녀가 머무는 곳엔 언제나 낙상홍의 붉은 온기와 하얀 눈토끼가 함께한다. 사람들은 지상에 눈이 내리면 비로소 프뤽사가 찾아왔음을 직감한다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• ibisPaint (Character Drawing & Object Asset Art)'],
    ],
    links: [
      ['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah-2023-2/project/스토리텔링기초/올림포스의-눈과-동심의-여신'],
      ['View Trivia', 'https://qr.me-qr.com/mobile/pdf/18810067'],
    ],
  },

  dfoo: {
    cat: 'awards', title: '디푸(D-Foo)',
    // 여러 장이면 맨 위가 옆으로 넘기는 슬라이드가 됨 (분홍 보드 → 기획서)
    heroes: ['a7652d_ba711fe6ca634a598d28b551186a987c~mv2.png', 'dfoo-sheet.png'],
    headline: "2026 디지털인문예술전공 신규 캐릭터 공모전 '우수상'",
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 디푸(D-Foo) >'],
      ['p', '“거대한 발자국으로 미래의 지평을 여는 개척자” 디지털인문예술전공의 새로운 상징 캐릭터를 제안한 공모전 출품작이다. 전설 속 빅풋(Bigfoot)을 모티브로, 불확실한 미래를 확신으로 개척해 나가는 디지털인문예술인의 자화상을 미니멀한 캐릭터로 시각화했다.'],
      ['sub', '[ Meaning ] : 디푸 (D-Foo)'],
      ['p', "현대 사회의 핵심 키워드와 전공이 지향하는 가치를 결합한 이름이다."],
      ['p', "• [ D ] : 디지털(Digital), 디자인(Design), 데이터(Data)를 통칭하는 'D'."],
      ['p', "• [ F ] : 우리 전공이 지향하는 가치인 미래(Future)의 'F'."],
      ['h', '[ Character Design ]'],
      ['img', 'dfoo-character.png', 300],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Minimalism & Humanism ] | 차갑고 복잡한 미래 기술을 따뜻한 인문학적 감성으로 정제하여, 극도로 단순화된 디자인적 해답을 제시했다.'],
      ['p', "• [ Milestone of the Future ] | 디푸의 거대한 발자국은 단순한 흔적이 아닌, 기술에 매몰되지 않고 인간의 삶을 풍요롭게 만드는 '미래 디자인'의 본질적인 가치를 상징한다."],
      ['p', '• [ Pioneering Leadership ] | 급변하는 기술 트렌드 속에서도 흔들리지 않는 확신을 가지고 앞장서 나가는 선구자적 정신을 투영했다.'],
      ['sub', "[ Motif ] : 왜 '빅풋(Bigfoot)'인가?"],
      ['p', '• [ 미지의 존재에서 미래의 상징으로 ] : 전설 속 미스터리한 존재인 빅풋을 현대적으로 재해석했다. 보이지 않는 곳에서 묵묵히 존재감을 드러내는 빅풋처럼, 복잡하고 혼란스러운 데이터의 숲에서 인간 중심의 새로운 지도를 그리는 개척자의 모습을 중의적으로 표현했다.'],
      ['p', "• [ 발자국(Footprint)의 무게감 ] : 빅풋의 가장 큰 특징인 '거대한 발'은 우리가 남기는 디자인과 데이터가 사회에 끼치는 영향력과 책임감을 상징한다. 정해진 길이 없는 황무지에서 내딛는 한 걸음이 곧 후세대의 길이 된다는 '퍼스트 무버(First Mover)'의 숙명을 담았다."],
      ['sub', '[ Storytelling ]'],
      ['p', "복잡한 정보 체계와 고도로 발달한 기술이 거대한 숲을 이루고 있는 '디지털 퓨처 포레스트(Digital Future Forest)'. 대다수가 현재의 기술적 성취에 안주하며 길을 잃을 때, 디푸는 데이터 사이의 숨겨진 맥락을 읽어내어 누구보다 앞서 다음 세대를 위한 새로운 경로를 설계한다."],
      ['h', '[ Character Goods ]'],
      ['img', 'dfoo-goods.png'],
      ['cap', '스티커 · 인형 · 폰케이스 · 키링 · 머그컵 · 리플렛 · 에코백 활용 예시'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Character Design & Vector Graphics)\n• Google Flow (Character Goods Mock-up)'],
    ],
    links: [['Visit Contest', 'https://dah-new-character-contest.vercel.app/award']],
  },

  psyche: {
    cat: 'awards', title: 'PROJECT: PSYCHE-TYPE',
    hero: 'a7652d_3d9ca7e1a44e42588a160d07e70f0c29~mv2.png',
    headline: "2026-1 제 18회 디지털인문예술전공 프로젝트 전시회 '우수상'",
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < PROJECT: PSYCHE-TYPE — König Schreibschrift & Druckschrift >'],
      ['p', "“숨겨진 내면을 활자로 기록하다” 게임 <콜 오브 듀티> 속 오퍼레이터 '쾨니히(König)'의 필적을 추적하고, 게임 속 설정을 바탕으로 그의 내면세계와 과거 배경을 심층 분석하여 재해석한 콘셉트 서체 시리즈이다. 거대한 체구 뒤에 숨겨진 유년 시절의 트라우마와 극심한 사회적 불안이라는 모순된 내면을, 상반된 두 가지 서체의 형태로 시각화했다."],
      ['sub', '[ Role ]'],
      ['p', 'Type Designer & Graphic Designer'],
      ['p', '• [ Character Analysis ] : AI(Gemini)와 협업하여 캐릭터의 설정·행동 패턴·심리적 방어 기제를 분석하고, 이를 서체의 조형 규칙으로 정리.'],
      ['p', '• [ Type Design ] : 분석 결과를 바탕으로 필기체·인쇄체 2종의 서체를 생성하고, Adobe Photoshop으로 자형을 다듬어 완성.'],
      ['p', "• [ Poster Design ] : 캐릭터의 '기밀 서류(Confidential File)' 콘셉트로 Adobe Illustrator에서 포스터를 디자인."],
      ['p', '• [ Web Publishing ] : 서체를 소개하고 배포하는 한국어·영어 웹사이트를 제작.'],
      ['h', '[ Typeface ]'],
      ['sub', '01 / König Schreibschrift : 정통 필기체'],
      ['p', '압도적인 체격과 군대의 엄격한 규율 속에서 탄생한 강인한 필기체이다. 거대한 손에서 나오는 묵직한 필압(Heavy)과, 작전 일지를 빠르게 기록하기 위해 물 흐르듯 이어지는 독일 정통 필기체의 연결선(Fluid)을 결합했다. 위압적인 외면과 달리 정규 교육으로 익힌 정통 필기체의 형태를 그대로 보존해, 그의 내면에 여전히 남아 있는 인간성을 드러낸다.'],
      ['sub', '02 / König Druckschrift : 강박적 인쇄체'],
      ['p', '어린 시절의 괴롭힘과 사회적 불안을 투영한 인쇄체이다. 타인의 시선과 평가를 두려워하는 방어 기제에서 출발해, 자를 대고 정렬한 듯 모든 글자의 높낮이(X-height)가 일정한 강박적인 형태를 띤다. 겉으로는 흠잡을 데 없이 단정하지만, 크게 확대해 보면 불안으로 인한 미세한 떨림과 날카로움이 자형 끝에 남아 있다.'],
      ['p', '• [ Hidden Doodles ] : 작전 일지 여백에 무의식적으로 남긴 듯한 낙서를 특수 기호(★ ☺ ♥ ■ ▲ 등)로 벡터화하여 두 서체에 모두 담았다.'],
      ['sub', '[ Design Concept ]'],
      ['p', "• [ Confidential File ] | 포스터 전체를 한 인물의 '기밀 서류'처럼 구성했다. 신상 카드, 'PROFILE COMPLETED' 도장, 행동 분석 보고서 형식을 빌려 서체 제작 과정이 인물을 조사하는 수사 기록처럼 읽히도록 연출했다."],
      ['p', '• [ Process as Narrative ] | DATA RETRIEVAL(필적 수집) → VECTOR RECONSTRUCTION(서체 분석 및 벡터 변환) → SYSTEM COMPILATION(서체 생성) → FINAL DEPLOYMENT(배포)의 4단계로 제작 과정을 정리해 보여 주었다.'],
      ['p', '• [ Contrast of Two Types ] | 규율을 상징하는 필기체와 방어 기제를 상징하는 인쇄체를 나란히 두어, 한 인물 안에 공존하는 상반된 내면을 대비시켰다.'],
      ['sub', '[ Distribution ]'],
      ['p', '2차 창작(팬 메이드) 서체로 전면 무료 배포하며, 개인적·비상업적 용도와 팬 콘텐츠에 한해 사용을 허용했다. 서체 파일(OTF/TTF)의 무단 재배포와 상업적 이용은 금지했다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Gemini (Character Analysis, Type Generation & Image Generation)\n• Adobe Photoshop (Glyph Editing & Image Editing)\n• Adobe Illustrator (Poster Design & Layout)\n• Wix (Typeface Website)'],
    ],
    links: [
      ['Visit Typeface Site (KR)', 'https://ixoxiartison.wixsite.com/koenig-typeface-kr'],
      ['Visit Typeface Site (EN)', 'https://ixoxiartison.wixsite.com/koenig-typeface'],
      ['Visit Exhibition', 'https://26-1-dah-exhibition.vercel.app/award'],
    ],
  },

  chok: {
    cat: 'design', title: '촉 (觸)',
    hero: 'chok-poster.png',
    headline: '2026-1 디지털인문예술 프로젝트 전시회 포스터 공모전 출품작',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 촉 (觸) >'],
      ['p', '“차가운 데이터가 인간의 손끝을 만나 온기를 입는 순간” 형태가 없는 디지털 세계를 불교적 세계관에 비유하여 풀어낸 전시 홍보 포스터이다. 인간과 기계가 만나는 최초의 접촉인 \'촉(觸)\'을 통해, 지역의 작은 이야기들이 전 세계로 뻗어나가 서로 경계를 허물고 어우러지는 거대한 \'디지털 만다라(Mandala)\'를 시각화했다.'],
      ['sub', '[ Meaning ] : 촉 (觸)'],
      ['p', '인간과 기계가 만나는 최초의 접촉. 이 손끝의 터치를 통해 차가운 데이터는 비로소 따뜻한 인간다움을 입는다.'],
      ['p', "• [ 공(空) ] : 형태가 없고 비어 있는 디지털 시스템은 불교의 '공(空)'과 닮아 있다."],
      ['p', "• [ 인드라망 ] : 전 세계가 인터넷으로 촘촘히 엮인 모습은, 우주의 모든 것이 연결되어 있다는 '인드라망'과 같다."],
      ['p', "• [ 자타불이(自他不二) ] : 손끝에서 시작된 연결은 나와 타인이 둘이 아니라는 '자타불이'의 정신을 증명한다."],
      ['sub', '[ Visual Narrative ]'],
      ['p', '화면 중심의 세 단계 컴퓨터는, 형태가 없는 디지털 데이터가 인간의 손길을 만나 생명력을 얻는 과정을 보여준다.'],
      ['p', '• [ 01 / 투명한 컴퓨터 ] : 어둠 속에서 떠오른 첫 번째 컴퓨터는 차갑고 투명한 기술 그 자체를 의미한다.'],
      ['p', "• [ 02 / 물들어 가는 컴퓨터 ] : 아래의 손에서 뿜어져 나오는 온기, 즉 '촉(觸)'에 반응하며 점차 변화하기 시작한다. 인간의 체온을 흡수할수록 색의 스펙트럼이 화려한 만다라처럼 넓어진다."],
      ['p', "• [ 03 / 손바닥 위의 컴퓨터 ] : 손바닥 위에 안착해 빛을 발하는 마지막 컴퓨터는, 기술이 더 이상 차가운 도구가 아니라 전 세계 사람들과 소통하는 따뜻한 매개체가 되었음을 뜻한다."],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Thermal Spectrum ] | 컴퓨터와 손을 물들이는 다채로운 열상(Thermal) 패턴은 각 지역 문화의 고유한 빛깔이자 인간의 체온을 상징한다.'],
      ['p', '• [ Cold to Warm ] | 투명한 유리 질감에서 열상 컬러로 이어지는 단계적 변화로, 기계적 완벽함 너머의 인간적인 온기가 디지털 시스템을 통해 퍼져나가는 연결의 미학을 표현했다.'],
      ['p', "• [ Digital Mandala ] | 어두운 배경 위에 컴퓨터를 감싸듯 펼쳐진 손들의 대칭 구도로, 서로 다른 문화가 조화롭게 어우러지는 '디지털 만다라'를 형상화했다."],
      ['sub', '※ [ Tools ]'],
      ['p', '• Gemini (Image Generation)\n• Adobe Illustrator (Typography & Layout)'],
    ],
    links: [['Visit Contest', 'https://26-1-dah-exhibition-poster-competit.vercel.app/content']],
  },

  pnr: {
    cat: 'interactive', title: 'POINT OF NO RETURN',
    heroes: ['game-title.png', 'game-stage2.png', 'game-stage3.png'],
    heroRatio: '16 / 10',
    headline: '2025-2 3D게임디자인 기말 프로젝트',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < POINT OF NO RETURN >'],
      ['p', '군인 캐릭터를 조작해 지뢰가 깔린 전장을 지나, 세 개의 스테이지를 통과해 탈출하는 3D 액션 어드벤처 게임이다. Unity로 스테이지 지형(맵) 제작부터 캐릭터 조작, 충돌 판정, 카메라, 사운드 연출까지 직접 구현했다.'],
      ['sub', '[ Role ]'],
      ['p', 'Solo Project — Game Design & Development'],
      ['p', '• [ Level Design ] : Terrain으로 스테이지별 지형(맵)을 직접 만들고, 자동차·헬기 같은 장애물과 지뢰를 배치해 진행 동선을 설계.'],
      ['p', '• [ Gameplay Programming ] : C# 스크립트로 이동·대시·점프, 충돌·트리거 판정, 스테이지 전환을 구현.'],
      ['p', '• [ Asset Integration ] : 캐릭터·차량·헬기 등은 외부 에셋을 활용하고, 애니메이션과 사운드를 연결해 게임에 맞게 구성.'],
      ['sub', '[ Game Rules ]'],
      ['p', '• 목표 : 스테이지 3까지 도달해 임무를 완료한다.\n• 실패 : 지뢰를 밟으면 \'MISSION FAILED\' 화면이 뜨고, 3초 뒤 메인 화면으로 돌아간다.\n• 조작 : WASD·방향키 이동 / Shift 대시 / Space 점프 / 마우스 우클릭 시점 회전 / 휠 확대·축소'],
      ['sub', '[ Key Features ]'],
      ['p', '• [ Player Control ] | Rigidbody 속도를 직접 제어해 이동을 구현하고, 땅에 닿아 있을 때만 점프되도록 해 연속 점프를 막았다. 캐릭터는 카메라 방향을 따라 부드럽게 회전한다.'],
      ['p', '• [ Trigger System ] | 지뢰(Mine)와 탈출구(ExitZone)에 트리거 영역을 두어, 닿는 순간 사망 처리 또는 다음 스테이지 로드가 일어나도록 했다.'],
      ['p', '• [ Third-Person Camera ] | 캐릭터를 따라가면서 마우스 우클릭으로 주변을 자유롭게 둘러보고, 휠로 확대·축소하는 궤도 카메라를 만들었다.'],
      ['p', '• [ Animation & Sound ] | Avatar Mask로 하체(걷기·뛰기)와 상체(사격) 애니메이션을 분리해 이동 중에도 사격할 수 있게 했다. 첫 사격 뒤에는 음성 경고가 늦게 울리고, 두 번째 사격부터는 적의 대응 사격음이 함께 재생되어 긴장감을 더한다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Unity (Level Design, Gameplay & UI)\n• C# (Gameplay Scripting)'],
    ],
    links: [],
  },

  webbook: {
    cat: 'interactive', title: '작은 동화책 — 연우의 대모험',
    heroes: ['webbook-home.png', 'webbook-book.png', 'webbook-christmas.png', 'webbook-special.png'],
    heroRatio: '16 / 10',
    headline: '2023-2 창의코딩 기말 프로젝트 : 나만의 웹사이트 만들기',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 작은 동화책 : 연우의 대모험 >'],
      ['p', '직접 쓰고 그린 동화책을 웹에서 읽을 수 있도록 만든 웹 동화책 사이트이다. 종이책보다 보여주기 편한 웹 동화책으로, 아이들이 비용·시간·공간의 제약 없이 언제 어디서든 동화를 즐기고, 그 안에 담긴 동심과 교훈을 함께 나눌 수 있기를 바랐다.'],
      ['sub', '[ Target ]'],
      ['p', '아이들과 부모, 어린이집 선생님'],
      ['sub', '[ Role ]'],
      ['p', 'Solo Project — Planning, Story, Illustration & Web Publishing'],
      ['p', "• [ Story & Illustration ] : 주인공 '연우'의 이야기를 직접 구상하고, 표지·삽화·캐릭터를 손으로 그려 제작."],
      ['p', '• [ Web Publishing ] : HTML·CSS로 홈, 동화책, 제작 과정, 소감 남기기, 크리스마스 특별 페이지까지 직접 구성.'],
      ['p', '• [ Narration ] : AI 보이스로 동화 낭독 음성을 만들어, 글을 읽기 어려운 아이도 들으면서 볼 수 있게 함.'],
      ['sub', '[ Site Structure ]'],
      ['p', "• [ Home : Delightful Reading ] | 연우가 '저와 함께 모험을 떠나봐요!'라고 말을 거는 첫 화면에서, 꽃 모양 메뉴를 눌러 각 페이지로 들어간다."],
      ['p', '• [ 동화책 : 연우의 대모험 ] | 펼친 책처럼 두 쪽씩 넘겨 보는 구성으로, 장면마다 그림과 글을 함께 배치했다.'],
      ['p', '• [ 제작 과정 ] | 스토리 구상부터 그림 제작까지의 과정을 영상으로 보여 준다.'],
      ['p', '• [ 소감 남기기 ] | 동화책을 읽은 뒤 감상과 의견을 남길 수 있는 설문형 페이지.'],
      ['p', '• [ Merry Christmas · 연우의 크리스마스 ] | 크리스마스 분위기로 꾸민 특별 페이지와, 연우에게 귀여운 동생이 생기는 번외 이야기.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Hand-drawn Warmth ] | 크레용으로 칠한 듯한 꽃·별 장식과 손글씨 느낌의 서체(Gaegu, 고운바탕)로 그림책의 따뜻한 분위기를 웹으로 옮겼다.'],
      ['p', '• [ Page Colors ] | 페이지마다 다른 색의 꽃 메뉴와 배경을 써서, 아이들도 색으로 지금 있는 곳을 알아보기 쉽게 했다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• HTML / CSS (Web Publishing)\n• AI Voice (Story Narration)'],
    ],
    links: [],
  },

  gongmyeong: {
    cat: 'design', title: '공명(共鳴) : 디지털의 파동',
    hero: 'a7652d_746eec0279f743ffbf679f8fff9959a6~mv2.png',
    headline: '2025-1 디지털인문예술 전시회 포스터 공모전 출품작',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 공명(共鳴) : 디지털의 파동 (Resonance: Digital Waves) >'],
      ['p', "본 프로젝트는 '글로컬(Glocal) 문화 의식'과 '지역과 세계 문화의 연결성'이라는 공모 주제를 시각적으로 해석한 작업이다. 중심에서 시작된 울림이 디지털 매체를 통해 전 세계로 확산되고, 서로 다른 가치들이 만나 새로운 시너지를 창출하는 과정을 기하학적 추상으로 표현했다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Graphic Designer'],
      ['p', '• [ Visual Metaphor ] : 중심에서 시작되어 사방으로 퍼져나가는 동심원의 파동(Wave)을 메인 모티프로 활용하여 지역적 울림이 세계로 확장되는 과정을 설계했다.'],
      ['p', '• [ 3D Graphic & Typography ] : Adobe Illustrator만을 활용하여 입체적인 파동의 형상과 반짝이는 질감, 타이포그래피를 일관된 시스템으로 구축했다.'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ 3D Modeling in Vector ] : 별도의 3D 프로그램을 사용하지 않고 Adobe Illustrator의 3D 및 재질 효과만으로 파동의 입체적인 볼륨감을 구현하여, 벡터 그래픽 특유의 깔끔함과 깊이감을 동시에 확보했다.'],
      ['p', '• [ Visual Effects ] : 파동의 끝단과 강조점에 반짝이는 효과(Sparkle)를 직접 제작·배치하여 디지털 예술의 역동적이고 신비로운 에너지를 시각적으로 극대화했다.'],
      ['p', '• [ Integrated Typography ] : 강렬한 블랙 톤의 타이포그래피를 파동의 흐름과 조화롭게 배치하여, 정보 전달력과 예술적 심미성을 동시에 만족시키는 레이아웃을 완성했다.'],
      ['sub', '[ Design Concept ]'],
      ['p', "• [ Resonance & Expansion ] | 파동의 중첩은 단순한 만남을 넘어선 '공명'을 의미하며, 이는 디지털인문예술전공이 지향하는 학문 간의 융합과 지역사회와 세계를 잇는 확산적 가치를 상징한다."],
      ['p', "• [ Visual Synergies through Overlapping ] | 불투명한 원형 레이어들이 서로 교차하고 중첩(Overlapping)되는 지점에서 색채가 심화되도록 연출함. 이는 서로 다른 문화적 가치가 결합(Convergence)하여 에너지가 증폭되는 시너지(Synergy)를 시각화한 것이며, '연결'을 통해 더 크고 깊은 가치가 생성됨을 의미한다."],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (3D Modeling, Typography, Sparkle Effects & Composition)'],
    ],
    links: [['Visit Contest', 'https://sites.google.com/view/l-hussxdah/content']],
  },

  sinho: {
    cat: 'design', title: '신호(信號) : 연결의 언어',
    hero: 'a7652d_be30121efa06445391aa782cd9554cdb~mv2.png',
    headline: '2024-2 디지털인문예술 전시회 포스터 공모전 출품작',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 신호(信號) : 연결의 언어 (Signal: The Language of Connection) >'],
      ['p', "본 프로젝트는 광활한 우주(Universe)를 배경으로, 지역(Local)의 문화적 메시지가 '연결'이라는 에너지를 통해 전 세계와 우주적 범위로 확장되는 과정을 시각화했다. 하단의 한글 '연결' 모스부호는 이 무한한 공간 속에서 길을 잃지 않고 소통되는 핵심 신호를 상징한다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Graphic Designer'],
      ['p', '• [ Universal Composition ] : Cinema 4D(C4D)를 활용하여 행성(Sphere)들이 부유하는 신비로운 우주 공간을 설계하고 렌더링했다.'],
      ['p', "• [ Signal Design ] : Adobe Illustrator를 통해 한글 '연결' 모스부호를 현대적인 그래픽 패턴으로 재해석하여 배치했다."],
      ['sub', '[ Contribution ]'],
      ['p', "• [ Cosmic Connectivity: '연결' ] : 포스터 하단의 점과 선은 한글 단어 '연결'의 모스부호입니다. 이는 칠흑 같은 우주 속에서 서로 다른 별(지역 문화)들을 잇는 보이지 않는 소통의 끈을 의미합니다."],
      ['p', '• [ Celestial Spheres ] : C4D로 구현한 다양한 질감의 구체들은 각기 다른 정체성을 가진 문화적 주체들을 상징하며, 이들이 우주적 질서 속에서 상호작용하며 공존하는 모습을 다층적 공간감으로 표현했습니다.'],
      ['p', '• [ Visual Harmony ] : 깊이 있는 어두운 우주 배경과 대비되는 발광체(Sparkle) 및 디지털 신호들을 배치하여, 보이지 않는 연결이 만들어내는 찬란한 가치를 시각화했습니다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Cinema 4D (Universe Modeling & Planet Rendering)\n• Adobe Illustrator (Typography, Morse Code Design & Layout)'],
    ],
    links: [['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah2024/home']],
  },

  'x-gon': {
    cat: 'design', title: "X Gon' Give It To Ya",
    hero: 'a7652d_09b49ab95d6e489fad228f41809cad1b~mv2.png',
    headline: '2024-1 제 14회 디지털인문예술 기말프로젝트 전시회 출품작',
    body: [
      ['sub', '[ Project ]'],
      ['p', "Project : < X Gon' Give It To Ya >"],
      ['p', "힙합 아티스트 DMX의 명곡인 X Gon' Give It To Ya 을 모티프로 한 타이포그래피 중심의 앨범 포스터이다. 가사가 가진 거칠고 공격적인 에너지를 그래피티 스타일과 노이즈 텍스처를 통해 현대적으로 재해석하였다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Graphic Designer'],
      ['p', '• [ Concept Planning ] : DMX의 곡 테마에 맞춘 비주얼 정체성 및 무드보드 설계.'],
      ['p', '• [ Artwork Production ] : 커스텀 타이포그래피 제작 및 멀티 레이어링 기법을 활용한 포스터 디자인 완성.'],
      ['sub', '[ Contribution ]'],
      ['p', "• [ Visual Contrast ] : 중앙의 해골 오브젝트와 강렬한 네온 컬러의 대비를 통해 디자인 의도인 '거친 생명력'을 극대화하여 표현하였다."],
      ['p', '• [ Graffiti Typography ] : 날카로운 획의 커스텀 타이포그래피를 제작하여, 텍스트가 단순한 정보 전달을 넘어 하나의 독립적인 그래픽 에셋으로서 역동적인 리듬감을 형성하도록 하였다.'],
      ['p', '• [ Grunge Texture & Overlapping ] : 거친 노이즈와 복잡하게 중첩된 패턴을 활용해 도시의 벽면(Wall)을 연상시키는 질감을 구현하였으며, 이를 통해 거리 예술 특유의 분위기를 완성하였다.'],
      ['p', "• [ Distortion & Onomatopoeia Layout ] : 'GRRR' 추임새를 원형으로 배치하고 해골 및 텍스트에 번짐과 왜곡 효과를 부여하여, 음악의 청각적 파동을 시각적인 역동성으로 해석하였다."],
      ['sub', '[ Design Concept ]'],
      ['p', "• [ Raw & Aggressive Energy ] | DMX 음악 특유의 거친 에너지를 시각적 '폭발력'으로 치환하여, 삶과 죽음 그리고 거리의 강인한 생명력을 담아내고자 하였다."],
      ['p', '• [ Cultural Connection ] | 힙합의 하위문화인 그래피티 아트와 거리 예술의 무질서함 속에서 발견되는 조형적 미학을 디자인의 핵심 테마로 설정하였다.'],
      ['p', '• [ Synesthetic Experience ] | 음악이 주는 청각적 타격감과 리듬감을 시각적으로 전이시켜, 보는 이로 하여금 음악의 에너지를 동시에 느낄 수 있는 공감각적 경험을 의도하였다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Custom Typography & Vector Graphic Design)\n• Adobe Photoshop (Filter Effects, Image Composition & Texture Rendering)'],
    ],
    links: [['Visit Exhibition', 'https://sites.google.com/glab.hallym.ac.kr/dah-2024-1/project/디지털-디자인-1/x-gon-give-it-to-ya']],
  },

  'leon-pro': {
    cat: 'design', title: 'LÉON: The Professional',
    hero: 'a7652d_954949d06c1447cf9bda031e806c7ac1~mv2.jpg',
    headline: 'LÉON: The Professional',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < LÉON: The Professional >'],
      ['p', "본 프로젝트는 영화 <레옹>의 서사를 한 인물의 실루엣 안에 압축하여 표현한 그래픽 포스터 디자인이다. 주인공 '레옹'의 일생을 관통하는 고독, 만남, 그리고 이별의 과정을 시각적 레이어링을 통해 연출하였다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Graphic Designer'],
      ['p', '• [ Visual Narrative Planning ] : 영화 <레옹>의 서사를 인물의 실루엣 안에 시간순으로 배치하는 시각적 스토리텔링 구조를 총괄 기획하였다.'],
      ['p', '• [ Symbolic Layout Design ] : 인물 간의 관계와 복선을 시각적 장치(선글라스, 총구 등)로 치환하여 배치하는 상징적 레이아웃을 설계하였다.'],
      ['p', '• [ Art Direction ] : 1990년대 필름 영화의 아날로그 감성을 재해석하여 강렬한 레드 컬러와 노이즈 질감을 활용한 전체적인 디자인 톤앤매너를 설정하였다.'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Narrative Layering & Masking ] : Adobe Photoshop의 고도화된 마스킹 기법을 활용하여 주인공의 실루엣 안에 다수의 영화 장면을 이질감 없이 중첩시켜 다층적인 서사를 완성하였다.'],
      ['p', '• [ Visual Storytelling ] : 인물 간의 관계와 복선(선글라스 속 빌런 등)을 레이아웃의 디테일로 녹여내어, 포스터 한 장으로 영화 전체의 맥락을 읽을 수 있도록 설계하였다.'],
      ['p', '• [ Texture & Color Grading ] : Adobe Photoshop을 활용하여 화이트 프레임과 노이즈 효과를 적용함으로써 필름 영화 특유의 질감을 재현하고 포스터의 완성도를 높였다.'],
      ['p', '• [ Typography Layout ] : 클래식한 세리프 체의 타이틀과 미니멀한 텍스트 배치를 통해 영화의 무게감과 세련미를 동시에 확보하였다.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Narrative Layering ] | 레옹의 얼굴 실루엣을 메인 프레임으로 활용하여, 그의 고독한 삶부터 마틸다와의 만남, 그리고 마지막 이별에 이르는 서사를 시간순으로 배치하였다.'],
      ['p', "• [ Symbolic Detail ] | 레옹의 선글라스 속에 빌런 '스탠'을 배치하여 그의 죽음을 암시하고, 마틸다의 총구가 스탠을 향하게 함으로써 복수의 대상을 시각적으로 명확히 드러내는 상징적 연출을 시도하였다."],
      ['p', '• [ Vintage Aesthetic ] | 1994년 개봉작이라는 시대적 배경을 반영하여, 강렬한 레드 톤의 배경과 입자감이 느껴지는 노이즈 텍스처를 활용해 빈티지한 아날로그 감성을 구현하였다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Photoshop (Image Composition, Masking, Texture Design & Color Grading)'],
    ],
    links: [],
  },

  silhouette: {
    cat: 'design', title: '지성의 실루엣',
    hero: 'a7652d_e23a4a9d4afd42e28151fba5d0f0e4e8~mv2.png',
    headline: '2025-1 일송기념도서관 장서표 디자인 공모전 출품작',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < 지성의 실루엣 (The Silhouette of Intelligence) >'],
      ['p', "한림대학교 일송기념도서관의 정체성 중 하나인 '다비드상'을 미니멀한 실루엣의 현대적 벡터 그래픽으로 재해석한 뒤, 그 위에 거친 판화 특유의 질감을 얹어 디지털의 차가운 느낌을 보완했다. 이 두 기법의 세련된 융합을 통해 장서표 특유의 고전적이고 따뜻한 아날로그 감성을 디자인했다."],
      ['sub', '[ Role ]'],
      ['p', 'Lead Graphic Designer'],
      ['p', '• [ Symbolic Narrative Planning ] : 다비드상의 서사와 도서관의 본질을 연결하여 디자인의 핵심 메타포를 설정.'],
      ['p', '• [ Visual Identity Direction ] : 흑백의 강렬한 대비를 통한 비주얼 아이덴티티를 수립하여 장서표로서의 신뢰감과 무게감을 확보.'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Digital Brush Work & Texturing ] : Adobe Photoshop의 브러쉬 툴을 활용해 목판화 특유의 거친 필치를 직접 드로잉하고, 극적인 명암 대비(Chiaroscuro)를 구현하였다.'],
      ['p', '• [ Typographic Reconstruction ] : Adobe Illustrator에서 판화 질감의 영문 폰트를 분해 후 한글로 재조합하는 실험적인 커스텀 타이포그래피를 완성하였다.'],
      ['p', "• [ Silhouette Composition ] : 책더미 위에 선 다비드의 실루엣을 중심으로 안정적인 레이아웃을 설계하여 '지성의 존재감'을 극대화하였다."],
      ['sub', '[ Design Concept ]'],
      ['p', "• [ The Victory of Intelligence ] | 골리앗이라는 거대한 무지(Ignorance)를 이겨낸 다비드의 '용기'를, 현대 사회에서 진리를 탐구하는 '지성'의 상징으로 치환하였다."],
      ['p', '• [ Light of Truth ] | 칠흑 같은 어둠 속에서 오직 지식(책)과 인간(다비드)만이 빛을 받는 연출을 통해, 지혜만이 인류를 구원할 유일한 등불임을 표현하였다.'],
      ['p', '• [ Modern Classicism ] | 전통적인 목판화의 투박한 미학과 현대적인 디지털 그래픽 기술을 융합하여, 고전의 가치를 현대적으로 계승하는 도서관의 역할을 상징화하였다.'],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Illustrator (Typographic Reconstruction & Layout Design)\n• Adobe Photoshop (Digital Drawing, Texture Rendering & Lighting Effects)'],
    ],
    links: [['Visit Contest', 'https://sites.google.com/view/l-huss-x/공모작/이지현']],
  },

  leon: {
    cat: 'design', title: 'LÉON',
    video: 'images/leon.mp4',
    poster: 'leon-poster.jpg',
    headline: 'LÉON',
    body: [
      ['sub', '[ Project ]'],
      ['p', 'Project : < LÉON >'],
      ['p', '본 프로젝트는 영화 <레옹>의 주요 서사와 캐릭터의 내면을 시각적으로 재해석한 타이틀 시퀀스 제작 작업이다. 캐릭터의 이름 자체가 곧 그들의 삶을 대변한다는 컨셉 아래, 타이포그래피와 장면의 유기적인 결합을 시도하였다.'],
      ['sub', '[ Role ]'],
      ['p', 'Lead Motion Designer'],
      ['p', '• [ Visual Storyboarding ] : 영화의 핵심 감정선을 따라 도입부, 전개, 결말에 이르는 영상의 시각적 서사 구조를 기획.'],
      ['p', '• [ Audio-Visual Sync Planning ] : 음악의 정박(On-beat)에 맞춘 타이틀 등장 시점과 교차 디졸브 타이밍을 설계하여 리드미컬한 편집 흐름을 수립.'],
      ['p', '• [ Graphic Identity Design ] : 트랙 매트(Track Matte) 기법을 활용한 타이틀 디자인과 전체적인 톤앤매너를 설정.'],
      ['sub', '[ Contribution ]'],
      ['p', '• [ Advanced Motion Editing ] : Adobe Premiere Pro를 활용하여 고난도의 트랙 매트 기법과 교차 디졸브를 구현하였으며, 텍스트와 영상 소스 간의 완벽한 합성을 완성하였다.'],
      ['p', '• [ Audio Engineering ] : 영상의 몰입도를 높이기 위해 보이스 오버와 배경음악을 정교하게 믹싱하고, 극단적인 J-컷 기법을 적용하여 청각적 임팩트를 구현하였다.'],
      ['p', '• [ Creative Sequencing ] : 음악의 변주에 맞춰 영화의 상징적 장면들을 배치하여 텍스트와 영상이 유기적으로 연결되는 시퀀스를 제작하였다.'],
      ['sub', '[ Design Concept ]'],
      ['p', '• [ Auditory Pre-emption (J-Cut) ] | 영상이 시작되기 전 오디오를 먼저 송출하는 J-컷 기법을 활용하여 시청자의 청각을 즉각적으로 자극하고, 캐릭터에 대한 몰입감을 극대화하였다.'],
      ['p', "• [ Typographic Identity ] | 'LEON'이라는 텍스트를 단순한 정보를 넘어 하나의 프레임으로 활용하였다. 글자 내부에 레옹과 마틸다의 유대감을 보여주는 장면들을 배치하여, \"이 이름이 곧 그들의 관계이자 정체성\"임을 상징화하였다."],
      ['p', "• [ Dual Narrative (IL EST) ] | 프랑스어 타이틀 'IL EST(그는 ~이다)'를 활용하여 킬러로서의 레옹과 마틸다를 지키는 레옹의 이중적 면모를 시각적으로 병치하였다."],
      ['sub', '※ [ Tools ]'],
      ['p', '• Adobe Premiere Pro (Video Editing, Motion Graphics & Audio Mixing)'],
    ],
    links: [['View Details', 'project.html?p=leon-detail']],
  },

  // 목록에는 없고 LÉON의 'View Details'로만 들어가는 페이지
  'leon-detail': {
    cat: 'design', hidden: true, title: 'LÉON - 연출 상세 설명',
    video: 'images/leon.mp4',
    poster: 'leon-poster.jpg',
    headline: 'LÉON',
    returnTo: 'leon',
    body: [
      ['sub', '[작품 기획 의도 및 연출 분석] : 타이틀백 < LÉON >'],
      ['p', '1994년에 개봉한 뤽 베송 감독의 영화인 < LÉON >의 타이틀백 제작.'],
      ['sub', '1. 도입부 (Intro): 청각적 선점과 캐릭터의 상징화'],
      ['p', '1) 청각적 연출 (J-Cut 활용):\n영상 시작 전, 검은 화면에서 오디오(목소리)를 먼저 송출하는 극단적인 J컷(J-Cut)기법을 활용한다. 이는 시각 정보 없이 청각에만 의존하게 하여 시청자의 즉각적인 집중을 유도한다.'],
      ['p', "2) 타이틀 디자인 (Track Matte):\n음악의 정박(On-beat)에 맞춰 메인 타이틀 'LEON'을 제시한다. (E의 악센트를 나중에 배치한 이유는 흥미와 재치를 주기 위함이다.)\n트랙매트(Track Matte)기법을 적용, 글자 내부에 레옹과 마틸다의 유대감을 보여주는 장면들을 교차 디졸브(Cross Dissolve)로 배치하여 둘의 관계성을 강조한다.\n마지막 글자에는 선글라스를 낀 레옹의 샷을 배치하여 \"이 이름이 곧 그 자신이다\"라는 아이덴티티를 명확히 하며 도입부를 맺는다."],
      ['sub', "2. 전개 (Main Body): 이중적 서사의 시각적 병치 'IL EST'"],
      ['p', "컨셉 및 상징: 프랑스어 타이틀 'IL EST(그는 ~이다)'를 통해 레옹의 존재와 운명을 중의적으로 조명한다."],
      ['p', "1) 화면 구성의 대비 (Visual Contrast):\n(1) 배경(Background): 마틸다와 함께 떠나는 장면을 배치하고 색조를 넣어 흑백(Black & White)으로 처리해, 이것이 레옹이 기억하는 '지나간 행복'이자 '추억'임을 암시한다.\n(2) 텍스트 내부(Fill): 반면 글자 안에는 레옹의 죽음을 암시하는 영상(악역의 살기 등)을 컬러로 삽입하여, 희망적인 배경과 비극적인 내부를 대비시킨다."],
      ['p', "2) 동선(Blocking)과 미장센:\n배경의 마틸다와 타이틀 속 스탠스필드(악역)가 모두 '왼쪽에서 오른쪽'으로 이동하는 동일 동선을 가진다. 타이틀(스탠스필드)이 배경(마틸다)을 가리며 등장하는 레이어링을 통해, 악역의 살기가 레옹의 행복한 기억을 침범하고 잠식하는 듯한 위기감을 시각적으로 구현한다."],
      ['sub', '3. 결말(Outro): 절제를 통한 여운의 극대화'],
      ['p', '1) 클라이맥스 편집 (Editing):\n레옹의 직접적인 사망 씬을 배제하고, 그를 죽이려는 스탠스필드의 살기 어린 표정에서 영상을 과감히 컷(Cut)한다. 이는 "설마 죽을까?"라는 긴장감과 결말에 대한 궁금증을 증폭시키는 장치로 작용한다.'],
      ['p', '2) 엔딩 연출 (Ending Sequence):\n(1) 블랙 스크린(Black Screen): 컷 이후 이어지는 정적과 검은 화면은 레옹의 죽음 뒤에 남겨진 공백과 상실감, 여운을 시각화한다.\n(2) 타이포그래피와 사운드: 영상 이미지 없이 오직 마틸다의 대사 타이핑과 힘없는 목소리(원본은 화분을 심는 장면임)만으로 화면을 채운다. 화려한 액션 뒤에 남은 정적을 통해 레옹의 죽음을 간접적으로 확정하고 깊은 여운을 남기며 마무리한다.'],
    ],
    links: [],
  },

  supporters: {
    cat: 'experience', title: '한림대학교 박물관 서포터즈 6기',
    headline: '[ 한림대학교 박물관 서포터즈 6기 ]',
    body: [
      ['h', '< 2024 메이커스 성과 전시회 포스터 디자인 >'],
      ['img', 'a7652d_bf216efc99db4651ad091fcaccdc26b5~mv2.png', 465],
      ['sub', "[ 디자인 컨셉: '연결'과 '조화' ]"],
      ['p', "• 유연한 흐름: 포스터 전체를 가로지르는 오렌지색 곡선은 '예술의 색'과 '메이커들의 열정(작품)'이 하나로 이어지는 흐름을 상징한다."],
      ['p', '• 여백의 미와 집중도: 화이트 배경을 베이스로 활용해 깔끔한 인상을 주면서도, 중앙의 타이포그래피에 시선이 집중되도록 설계했다.'],
      ['sub', '[ 기술적 디테일 (Technical Highlights) ]'],
      ['p', '• Photoshop (이미지 합성과 리터칭): 부채, 무드등, 공예품 등 실제 작품 사진의 배경을 정교하게 제거 후 효과를 더해 리터칭 했다.'],
      ['p', "• Illustrator (레이아웃과 정밀 설계): 가독성이 중요한 전시 정보를 하단에 안정적으로 배치하고, 로고 간의 균형 맞추고, 메인 타이틀의 폰트 선택이 전시의 주제인 '예술'과 '메이커스'의 아날로그적인 따뜻함을 잘 전달했다."],
      ['imgs', [
        'a7652d_82100a60ebb64c65a5f3d7ca9e94c879~mv2.png',
        'a7652d_bdef69d122414a74aaf7f4a12e58e5d1~mv2.jpg',
        'a7652d_aa1612ae9de048de91d8b0ce73b68c4b~mv2.jpg',
        'a7652d_8efa987f6f0e4131bbd11053c246abba~mv2.png',
        'a7652d_821149fc6ed84eefb8ff4a5f244cec5f~mv2.png',
      ]],
      ['h', '< 2024-2 5기 시민박물관대학 L자 홀더 디자인 >'],
      ['img', 'a7652d_a6b52a6bc1284cb9855174dac3849d85~mv2.png'],
      ['sub', "[ 디자인 컨셉: '시각적 일관성'과 '매체적 확장' ]"],
      ['p', "• 아이덴티티 계승: 기존 메인 포스터와 배너에서 사용된 파스텔 톤의 그라데이션과 유연한 곡선 패턴을 그대로 가져와, '제5기 시민박물관대학'만의 브랜드 아이덴티티를 일관성 있게 유지했다."],
      ['p', '• 오브제의 재배치: 세로형 배너와 포스터에 분산되어 있던 원형 오브제들을 제작 후 L홀더의 앞·뒷면 공간에 맞춰 균형 있게 재배치하여, 단독 굿즈로서의 완성도를 높였다.'],
      ['p', '• 여백과 정보의 조화: 포스터의 시원한 공간감을 유지하면서도, L홀더 뒷면에는 상세 강의 일정표를 배치해 실용적인 홍보물의 기능을 극대화했다.'],
      ['sub', '[ 기술적 디테일 (Technical Highlights) ]'],
      ['p', "• Illustrator (벡터 그래픽 및 특수 효과): 일러스트레이터의 그라디언트 기능(Mesh Tool)을 활용해 분위기와 어울리는 오묘한 빛을 내는 입체적인 구체를 구현했다. 또한 블렌드 도구(Blend Tool) 활용해 유연하게 흐르는 선들은 블렌드 도구를 사용하여 단계별 변화를 주었으며, 이를 통해 '전통의 전승'이라는 추상적인 개념을 시각적 리듬감으로 표현했다."],
      ['imgs', [
        'a7652d_3b51d39d937c4253b6358feb8c537c98~mv2.png',
        'a7652d_7b6aa4ab2eda4786bb01c834085db620~mv2.png',
      ]],
      ['cap', '기존 메인 포스터와 배너'],
    ],
    links: [],
  },

  researcher: {
    cat: 'experience', title: '한림대학교 박물관 보조연구원',
    headline: '[ 한림대학교 박물관 보조연구원 ]',
    body: [
      ['h', '< 한림대학교 박물관 캐릭터 제작 >'],
      ['img', 'a7652d_72bcb4470e28404ebb0e80a2dd2d94a8~mv2.png', 359],
      ['h', "AI 도슨트 '뮤지온(Muse-on)'"],
      ['sub', "[ 디자인 컨셉: '역사'와 '일상' ]"],
      ['p', "• 전통 유물의 현대적 변주: 박물관 소장 유물인 '오리모양토기'의 실루엣을 둥글고 친근한 새의 형태로 재해석하여, 고대 유물이 가진 역사적 가치와 일상적인 친근함으로 풀어냈다."],
      ['p', "• 지성과 기술의 융합: 신뢰감과 스마트함을 상징하는 블루 컬러를 메인 톤으로 설정하고, 'AI 도슨트'로서의 박물관과 관람객의 연결을 다정하게 이어주는 친근한 소통의 매개체로 표현했다."],
      ['sub', '[ 기술적 디테일 (Technical Highlights) ]'],
      ['p', '• Illustrator (정밀한 벡터 설계와 디자인): 캐릭터의 외곽 라인을 깔끔한 벡터 그래픽으로 구현하고, 톤인톤(Tone-in-Tone) 배색을 통해 평면적일 수 있는 캐릭터에 안정감 있는 입체감을 부여했다.'],
      ['img', 'a7652d_55b2c0e1629a417ea13cf4b5bbed65f7~mv2.png', 414],
      ['cap', '시안 1 · 시안 2 · 시안 3'],
      ['imgs', [
        'a7652d_e27e5237532f407cb4104ece4be273aa~mv2.png',
        'a7652d_27a0e1095c684c4da4b9824c97d9198a~mv2.png',
      ]],
      ['cap', '스티커 굿즈'],
      ['p', '• 유물 정리 및 세척\n• 유물, 유적지 일러스트 선 따기 작업\n• 박물관 내 기획 전시실, 유물보관실 정리\n• 박물관 캐릭터 제작'],
    ],
    links: [],
  },
};
